# Generated by Django 6.0.5 on 2026-06-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
    ]
